name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Install dependencies
      - name: Install Dependencies
        run: |
          npm install

      # Run tests
      - name: Run Tests
        run: |
          npm test

  deploy:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Deploy to staging
      - name: Deploy to Staging
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker build -t your-image-name .
          docker tag your-image-name your-repo/your-image-name:staging
          docker push your-repo/your-image-name:staging

  production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: deploy
    if: github.ref == 'refs/heads/main'

    steps:
      # Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Deploy to production
      - name: Deploy to Production
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker build -t your-image-name .
          docker tag your-image-name your-repo/your-image-name:latest
          docker push your-repo/your-image-name:latest

