name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build the Docker image
    - name: Build Docker image
      run: |
        docker build -f .github/workflows/Dockerfile -t abeer177/glowvibeapp:staging .
        docker push abeer177/glowvibeapp:staging
    # Push to Docker Hub (Staging)
    - name: Push Docker image to Docker Hub (Staging)
      run: |
        docker tag abeer177/glowvibeapp:staging abeer177/glowvibeapp:latest
        docker push abeer177/glowvibeapp:staging
        docker push abeer177/glowvibeapp:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Deploy to Production
    - name: Deploy to Production
      run: |
        echo "Deploying to production..."
        # Add your deployment scripts or commands here
        # Example:
        # docker run -d -p 80:8000 abeer177/glowvibeapp:latest

